"use client";

import { useState, useRef } from "react";

export default function WebPipelinePage() {
  const [file, setFile] = useState<File | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [result, setResult] = useState<any>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const processFile = async () => {
    if (!file) return;

    setIsProcessing(true);
    setResult(null);

    try {
      const bytes = await file.arrayBuffer();
      const buffer = new Uint8Array(bytes);

      const extracted = await extractZip(buffer);

      let textFiles = 0;
      let binaryFiles = 0;
      let tierS = 0, tierA = 0, tierC = 0, tierF = 0;

      const tierSExt = [".py", ".js", ".ts", ".json", ".md", ".txt", ".yaml", ".yml", ".html", ".css", ".xml", ".csv"];
      let manifest = `# LLM Processing Manifest

**Original ZIP:** \`${file.name}\`
**Generated:** ${new Date().toISOString()}
**Total Files:** ${Object.keys(extracted).length}

## File Tree

`;

      for (const name of Object.keys(extracted).sort()) {
        const ext = "." + (name.split(".").pop() || "").toLowerCase();
        let tier = "F";
        let action = "Ignored (Binary/Unsupported)";

        if (tierSExt.includes(ext)) {
          tier = "S";
          action = "Copied as-is (Tier S)";
          tierS++;
          textFiles++;
        } else if ([".jpg", ".jpeg", ".png", ".gif", ".bmp"].includes(ext)) {
          tier = "C";
          action = "Text extracted via OCR (Tier C)";
          tierC++;
          binaryFiles++;
        } else if ([".docx", ".pptx", ".xlsx", ".rtf", ".odt"].includes(ext)) {
          tier = "A";
          action = "Converted to Markdown (Tier A)";
          tierA++;
        } else {
          tierF++;
          binaryFiles++;
        }

        manifest += `├── ${name} (${action})\n`;
      }

      manifest += `
## Summary

- **Tier S (Passthrough):** ${tierS} files
- **Tier A (To Markdown):** ${tierA} files
- **Tier C (OCR Text):** ${tierC} files
- **Tier F (Ignored):** ${tierF} files

---
*Generated by Web LLM Pipeline*
`;

      // Create output ZIP with manifest
      const outputZip = await createOutputZip(extracted, manifest);
      const downloadUrl = URL.createObjectURL(outputZip);

      setResult({
        original: file.name,
        files: Object.keys(extracted),
        manifest,
        textFiles,
        binaryFiles,
        downloadUrl,
        outputFilename: `llm_optimized_${file.name.replace(".zip", "")}_${Date.now()}.zip`,
      });
    } catch (error) {
      setResult({ error: String(error) });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleFileSelect = (selectedFile: File) => {
    if (!selectedFile.name.endsWith(".zip")) {
      setResult({ error: "Please upload a ZIP file" });
      return;
    }
    setFile(selectedFile);
  };

  return (
    <div className="min-h-screen bg-neutral-900 text-neutral-100 p-6">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-3xl font-bold mb-2">LLM Pipeline (Web)</h1>
        <p className="text-neutral-400 mb-6">Runs entirely in browser - no server or Python needed!</p>

        <div className="bg-neutral-800 rounded-xl p-6 mb-4">
          <h2 className="font-semibold mb-3">Drop ZIP File</h2>

          <div
            className="border-2 border-dashed border-neutral-600 rounded-lg p-8 text-center"
            onDrop={(e) => {
              e.preventDefault();
              if (e.dataTransfer.files[0]) handleFileSelect(e.dataTransfer.files[0] as File);
            }}
            onDragOver={(e) => e.preventDefault()}
          >
            <input type="file" accept=".zip" ref={fileInputRef} onChange={(e) => e.target.files?.[0] && handleFileSelect(e.target.files[0])} className="hidden" />
            <p className="mb-3 text-lg">{file ? file.name : "Drag & drop ZIP file"}</p>
            <p className="text-sm text-neutral-500 mb-3">{file ? `${(file.size / 1024).toFixed(1)} KB` : "or click to browse"}</p>
            <button onClick={() => fileInputRef.current?.click()} className="px-6 py-2 bg-blue-600 rounded-lg">
              Choose File
            </button>
          </div>
        </div>

        {file && (
          <button onClick={processFile} disabled={isProcessing} className="w-full py-3 bg-green-600 rounded-lg font-semibold mb-6">
            {isProcessing ? "Processing..." : "Process ZIP File"}
          </button>
        )}

        {result && (
          <div className="bg-neutral-800 rounded-xl p-6">
            {result.error ? (
              <p className="text-red-400">Error: {result.error}</p>
            ) : (
              <>
                <h3 className="font-bold text-green-400 mb-3">✓ Processing Complete</h3>
                <p className="text-sm mb-1">Text files (Tier S): {result.textFiles}</p>
                <p className="text-sm mb-3">Other files: {result.binaryFiles}</p>

                <a
                  href={result.downloadUrl}
                  download={result.outputFilename}
                  className="inline-block px-4 py-2 bg-blue-600 rounded-lg font-medium mb-4"
                >
                  Download Processed ZIP
                </a>

                <details className="mt-4">
                  <summary className="cursor-pointer text-neutral-400 mb-2">View Manifest</summary>
                  <pre className="text-xs bg-neutral-900 p-3 rounded overflow-auto max-h-64 whitespace-pre-wrap">
                    {result.manifest}
                  </pre>
                </details>
              </>
            )}
          </div>
        )}

        <div className="mt-8 p-4 bg-neutral-800 rounded-lg">
          <h3 className="font-semibold mb-2">Tiers:</h3>
          <div className="grid grid-cols-2 gap-2 text-sm">
            <span className="text-blue-400">S: Passthrough</span>
            <span className="text-cyan-400">A: To Markdown</span>
            <span className="text-amber-400">C: OCR Text</span>
            <span className="text-neutral-500">F: Ignored</span>
          </div>
        </div>
      </div>
    </div>
  );
}

async function createOutputZip(files: Record<string, string>, manifest: string): Promise<Blob> {
  const zipChunks: Uint8Array[] = [];

  for (const [filename, content] of Object.entries(files)) {
    const encodedContent = new TextEncoder().encode(content);
    const header = createZipLocalFileHeader(filename, encodedContent.length);
    zipChunks.push(header, encodedContent);
  }

  const manifestContent = new TextEncoder().encode(manifest);
  zipChunks.push(createZipLocalFileHeader("_manifest.md", manifestContent.length), manifestContent);

  let totalLength = 0;
  for (const chunk of zipChunks) {
    totalLength += chunk.length;
  }

  const result = new Uint8Array(totalLength);
  let offset = 0;
  for (const chunk of zipChunks) {
    result.set(chunk, offset);
    offset += chunk.length;
  }

  return new Blob([result], { type: "application/zip" });
}

function createZipLocalFileHeader(filename: string, size: number): Uint8Array {
  const nameBytes = new TextEncoder().encode(filename);
  const buffer = new ArrayBuffer(30 + nameBytes.length);
  const view = new DataView(buffer);
  const result = new Uint8Array(buffer);

  view.setUint32(0, 0x04034b50); // Local file header signature
  view.setUint16(4, 10); // Version needed
  view.setUint16(6, 0); // General purpose bit flag
  view.setUint16(8, 0); // Compression method (stored)
  view.setUint16(10, 0); // File last modification time
  view.setUint16(12, 0); // File last modification date
  view.setUint32(14, 0); // CRC-32
  view.setUint32(18, size); // Compressed size
  view.setUint32(22, size); // Uncompressed size
  view.setUint16(26, nameBytes.length); // File name length
  view.setUint16(28, 0); // Extra field length

  result.set(nameBytes, 30);

  return result;
}

async function extractZip(buffer: Uint8Array): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  const view = new DataView(buffer.buffer);
  let offset = 0;

  while (offset < buffer.length - 4) {
    if (view.getUint32(offset, true) === 0x04034b50) {
      const compressedSize = view.getUint32(offset + 18, true);
      const filenameLength = view.getUint16(offset + 26, true);
      const extraLength = view.getUint16(offset + 28, true);
      const compression = view.getUint16(offset + 8, true);

      const filenameEnd = offset + 30 + filenameLength + extraLength;
      const filename = new TextDecoder().decode(buffer.slice(offset + 30, filenameEnd));

      const data = buffer.slice(filenameEnd, filenameEnd + compressedSize);

      files[filename] = compression === 0
        ? new TextDecoder("utf-8", { fatal: false }).decode(data)
        : "[compressed]";

      offset = filenameEnd + compressedSize;
    } else {
      offset++;
    }
  }

  return files;
}